name: tangerinesamurai
favicon: null
layout_spectrum: 0.08812
typography_spectrum: 0.57425
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090d0c'
    - '#465252'
    - '#828b8a'
    - '#a1aaa9'
    - '#e4e5e9'
  brandStrength: 0.625
  lightness: 0.8098112379666418
  saturation: 0.6963418470695615
  rhythmicContrast: 0.5
purpose: []
